name: build
on:
  push:
jobs:
  build:
    name: Build & Push Container
    runs-on: ubuntu-latest
    env:
      APP: chrony
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/amd64,linux/arm64
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/${{ env.APP }}:latest
            ${{ github.repository_owner }}/${{ env.APP }}:latest
